#ifndef VERSION_H
#define VERSION_H

#define ATM_CONTROLLER_VERSION_MAJOR 1
#define ATM_CONTROLLER_VERSION_MINOR 0
#define ATM_CONTROLLER_VERSION_PATCH 0

#define ATM_CONTROLLER_VERSION_STRING "1.0.0"

#endif // VERSION_H